version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: next-auction-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: next_auction_db
    ports:
      - "5434:5432"
    volumes:
      - next_auction_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  next_auction_postgres_data:
